# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone SE",
  "iPhone X",
  "iPad Pro (12.9-inch)",
  "iPad Pro (9.7-inch)" 
  ])

  languages([
"en-US", 
# "it-IT" 
 ])
 
scheme("fit UITests") 
output_directory "./fastlane/screenshots"
concurrent_simulators false
localize_simulator true 
clear_previous_screenshots(true)